### ISSUE TITLE
Browser freeze on draw

### ISSUE THREAD

**Issue by jeena** [logsol/chuck.js#103]
Could be related to #96

**Comment by logsol** [comment]
As we found with the first version of the recorder (and firefox) the issue seems to be related to the SolveTOI inside the box2d step function. 

It seems that this is a box2d bug that might be in our version. Erin (the box2d creator) built in a limit that prevents infinite loops like this: https://code.google.com/p/box2d/issues/detail?id=143#c2

**Comment by logsol** [comment]
so ive been doing some deeper digging and implemented a limit at the given position, but it did not fix the problem.

I narrowed it down to the "for (;;) {" loop in line 2424, wich just breaks if certain conditions apply, which are not in our case.

I would suggest to work on our asm branch and implement a newer version of box2d and see if it still  happens.
